[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "moviepy>=2.1.1",
    "pytube>=15.0.0",
    "whisper>=1.1.10",
    "youtube-transcript-api>=0.6.3",
]
